export const cores = {
  fundo: "#f8f9ff",
  superficie: "#f8f9ff",
  superficieContainerBaixa: "#eff4ff",
  superficieContainerMinima: "#ffffff",
  superficieContainerAlta: "#dee9fc",
  superficieContainer: "#e6eeff",
  sobreFundo: "#121c2a",
  sobreSuperficie: "#121c2a",
  sobreSuperficieVariante: "#3e4943",
  primaria: "#006c4b",
  sobrePrimaria: "#ffffff",
  primariaContainer: "#5bc89a",
  sobrePrimariaContainer: "#005137",
  secundaria: "#006c48",
  secundariaContainer: "#8af8c1",
  sobreSecundariaContainer: "#00734c",
  terciaria: "#825500",
  terciariaContainer: "#eca73e",
  sobreTerciariaContainer: "#623f00",
  contorno: "#6e7a72",
  contornoVariante: "#bdcac0",
  erro: "#ba1a1a",
};
